openapi: 3.0.3
info:
  title: Tournament REST API
  version: "1.0"
servers:
  - url: http://127.0.0.1:8000
    description: Tournament API (local)
  - url: http://127.0.0.1:4010
    description: Prism Mock API (local)
paths:
  /api/discord/auth/callback:
    get:
      operationId: discordAuthCallback
      description: Сервер обменивает код у [Discord'а](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-access-token-exchange-example) на `access_token`, получает с его помощью доступ к id пользователя. Записывает у себя в БД и возвращает токен, по которому можно идентифицировать и дать доступ клиенту к запросам.
      parameters:
        - required: true
          style: deepObject
          explode: true
          schema:
            allOf:
              - $ref: "#/components/schemas/discord_code"
            example: DPaqMZlxJIegXUDC2UM4hQ878cWTDA
          name: code
          in: query
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/auth_token"
      tags:
        - /api
  /api/discord/get-user-data:
    get:
      operationId: getDiscordUserData
      description: Возвращает [User Data](https://discord.com/developers/docs/resources/user#user-object) из Discord'а.
      parameters:
        - required: true
          schema:
            $ref: "#/components/schemas/auth_token"
          name: Authorization
          in: header
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "12345"
                  nickname:
                    type: string
                    example: Agent
                  avatar:
                    type: string
                    example: hash
                required:
                  - id
                  - nickname
                  - avatar
                additionalProperties: false
      tags:
        - /api
components:
  schemas:
    auth_token:
      pattern: "[A-Za-z0-9+\\/=]+"
      type: string
    discord_code:
      type: string
      example: DPaqMZlxJIegXUDC2UM4hQ878cWTDA
